# Generated by Django 2.2.7 on 2019-11-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeBox', '0002_auto_20191114_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='_author_favorites_+', to='recipeBox.RecipeItem'),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(default='foo'),
            preserve_default=False,
        ),
    ]
