# Generated by Django 2.2.7 on 2019-11-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeBox', '0003_auto_20191125_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='recipeBox.RecipeItem'),
        ),
    ]
